In [1]:
people = {
    'first' : ['Ram', 'Shyam', 'Binod'],
    'last' : ['Das', 'Bahadur', 'Chaudhary'],
    'email' : ['ramdas@gmail.com', 'shyambdr@gmail.com', 'binodchy@gmail.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first       last               email
0    Ram        Das    ramdas@gmail.com
1  Shyam    Bahadur  shyambdr@gmail.com
2  Binod  Chaudhary  binodchy@gmail.com

In [15]:
# Setting Our Own Indexes [Email As An Index]
df.set_index('email', inplace = True)

In [9]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [16]:
df

                    first       last
email
ramdas@gmail.com      Ram        Das
shyambdr@gmail.com  Shyam    Bahadur
binodchy@gmail.com  Binod  Chaudhary

In [21]:
df.loc['shyambdr@gmail.com']

first      Shyam
last     Bahadur
Name: shyambdr@gmail.com, dtype: object

In [25]:
# Reseting The Index:
df.reset_index(inplace = True)

In [26]:
df

                email  first       last
0    ramdas@gmail.com    Ram        Das
1  shyambdr@gmail.com  Shyam    Bahadur
2  binodchy@gmail.com  Binod  Chaudhary