In [1]:
people = {
    'first' : ['Ram', 'Shyam', 'Binod'],
    'last' : ['Das', 'Bahadur', 'Chaudhary'],
    'email' : ['ramdas@gmail.com', 'shyambdr@gmail.com', 'binodchy@gmail.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first       last               email
0    Ram        Das    ramdas@gmail.com
1  Shyam    Bahadur  shyambdr@gmail.com
2  Binod  Chaudhary  binodchy@gmail.com

In [5]:
df['first'] + ' ' + df['last']

0            Ram Das
1      Shyam Bahadur
2    Binod Chaudhary
dtype: object

In [6]:
# Adding New Columns In Our DataFrame:
df['full_name'] = df['first'] + ' ' + df['last']

In [7]:
df

   first       last               email        full_name
0    Ram        Das    ramdas@gmail.com          Ram Das
1  Shyam    Bahadur  shyambdr@gmail.com    Shyam Bahadur
2  Binod  Chaudhary  binodchy@gmail.com  Binod Chaudhary

In [8]:
# Removing Columns Using Drop Method:
df.drop(columns = ['first', 'last'], inplace = True)

In [9]:
df

                email        full_name
0    ramdas@gmail.com          Ram Das
1  shyambdr@gmail.com    Shyam Bahadur
2  binodchy@gmail.com  Binod Chaudhary

In [10]:
# Spliting The Full Name Columns:
df['full_name'].str.split(' ')

0            [Ram, Das]
1      [Shyam, Bahadur]
2    [Binod, Chaudhary]
Name: full_name, dtype: object

In [11]:
# Spliting Permanently:
df['full_name'].str.split(' ', expand = True)

       0          1
0    Ram        Das
1  Shyam    Bahadur
2  Binod  Chaudhary

In [12]:
# Assing Columns To Our Splited Value:
df[['first', 'last']] = df['full_name'].str.split(' ', expand = True)

In [13]:
df

                email        full_name  first       last
0    ramdas@gmail.com          Ram Das    Ram        Das
1  shyambdr@gmail.com    Shyam Bahadur  Shyam    Bahadur
2  binodchy@gmail.com  Binod Chaudhary  Binod  Chaudhary

In [15]:
# Adding New Row In Our Existing DataFrame:
# New row as a DataFrame
new_row = pd.DataFrame([{'first': 'Mohan'}])

# Concatenate
df = pd.concat([df, new_row], ignore_index=True)

# --------------- OR ------------------------
# df = pd.concat([df, pd.DataFrame([{'first': 'Mohan'}])], ignore_index=True)

In [16]:
df

                email        full_name  first       last
0    ramdas@gmail.com          Ram Das    Ram        Das
1  shyambdr@gmail.com    Shyam Bahadur  Shyam    Bahadur
2  binodchy@gmail.com  Binod Chaudhary  Binod  Chaudhary
3                 NaN              NaN  Mohan        NaN

In [17]:
# Creating Another DataFrame:
people = {
    'first' : ['Tony', 'Steve'],
    'last' : ['Stark', 'Rogers'],
    'email' : ['IronMan@avgen.com', 'CapatinAmerica@avgen.com']
}

df2 = pd.DataFrame(people)

In [18]:
df2

   first    last                     email
0   Tony   Stark         IronMan@avgen.com
1  Steve  Rogers  CapatinAmerica@avgen.com

In [19]:
# Making One DataFrame Of Two DataFrame:
df = pd.concat([df, df2], ignore_index = True)

In [20]:
df

                      email        full_name  first       last
0          ramdas@gmail.com          Ram Das    Ram        Das
1        shyambdr@gmail.com    Shyam Bahadur  Shyam    Bahadur
2        binodchy@gmail.com  Binod Chaudhary  Binod  Chaudhary
3                       NaN              NaN  Mohan        NaN
4         IronMan@avgen.com              NaN   Tony      Stark
5  CapatinAmerica@avgen.com              NaN  Steve     Rogers

In [25]:
# Deleting Row:
df.drop(index = 5, inplace = True)

In [26]:
df

                email        full_name  first       last
0    ramdas@gmail.com          Ram Das    Ram        Das
1  shyambdr@gmail.com    Shyam Bahadur  Shyam    Bahadur
2  binodchy@gmail.com  Binod Chaudhary  Binod  Chaudhary
3                 NaN              NaN  Mohan        NaN
4   IronMan@avgen.com              NaN   Tony      Stark

In [28]:
# Deeting Row Using Conditional:
filt = df['last'] == 'Chaudhary'
df.drop(index = df[filt].index)

                email      full_name  first     last
0    ramdas@gmail.com        Ram Das    Ram      Das
1  shyambdr@gmail.com  Shyam Bahadur  Shyam  Bahadur
3                 NaN            NaN  Mohan      NaN
4   IronMan@avgen.com            NaN   Tony    Stark